using System.ComponentModel;
using System.Numerics;

namespace universe_simulator.cheat;

public class Particle: IParticle
{
    public double energy { get; set; }
    public Vector3 momentum { get; set; }
    public Vector3 position { get ; set ; }

    public Particle(double energy, Vector3 position, Vector3 momentum)
    {
        this.energy = energy;
        this.position = position;
        this.momentum = momentum;
    }

    public bool Tick()
    {
        position += momentum;
        return true;
    }
}

public class Photon : Particle
{
    public Photon(ulong frequency, IParticle source, Vector3 dir): 
        base(frequency * CONSTANTS.PLANCK_CONSTANT, source.position, dir)
    {        
        this.direction = dir;
        this.source = source;
    }

    public Vector3 direction { get; } // The direction would be relative to an observer
    public double frequency { get { return energy / CONSTANTS.PLANCK_CONSTANT; }} // The wavelength determines the type of photon (light, gamma, radio wave) as well as the energy
    public IParticle source { get; } // Photons are generated by eletrons
    public IParticle? target { get; } // Photons will eventually be absorbed by electrons on a target
    // Other properties and methods can be added here
    public new bool Tick()
    {
        return base.Tick();
    }
}

public class Matter : Particle
{
    public Matter(Vector3 pos, Vector3 dir, uint numProtons = 1, uint numNeutrons = 0, uint numElectrons = 1) :
        // Energy of matter based on e - mc^2     
        base((numProtons * CONSTANTS.PROTON_MASS + numNeutrons * CONSTANTS.NEUTRON_MASS + numElectrons * CONSTANTS.ELECTRON_MASS) * CONSTANTS.SPEED_LIGHT * CONSTANTS.SPEED_LIGHT, pos, dir)
    {
    }
    
    // Other properties and methods can be added here
    public new bool Tick()
    {
        return base.Tick();
    }
}