using System.ComponentModel;
using System.Numerics;

namespace universe_simulator.cheat;

public class Particle: IParticle
{
    public double energy { get; set; }
    public Vector3 momentum { get; set; }
    public double mass  { get; set; }
    public Particle(double energy, Vector3 momentum, double mass)
    {
        this.energy = energy;
        this.momentum = momentum;
        this.mass = mass;
    }
}

public class Photon : Particle
{
    public Photon(double energy, Vector3 momentum, double mass, Particle source) : base(energy, momentum, mass)
    {
        this.source = source;
    }

    public Vector3 direction { get; } // The direction would be relative to an observer
    public double wavelength { get; } // The wavelength determines the type of photon (light, gamma, radio wave) as well as the energy
    public Particle source { get; } // Photons are generated by eletrons
    public Particle? target { get; } // Photons will eventually be absorbed by electrons on a target
    // Other properties and methods can be added here
}